# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'THRefreshBaseOnMJRefresh' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for THRefreshBaseOnMJRefresh
pod 'MJRefresh', '~> 3.1.15.6'

end
